ext_if = "pppoe0"                # The external (WAN) interface used by your ISP
int_if = "igc0"                  # The internal (LAN) interface for your local network
local_net = $int_if:network      # Dynamically calculates your LAN subnet (e.g., 192.168.90.0/24)

table <martians> { 0.0.0.0/8 10.0.0.0/8 127.0.0.0/8 169.254.0.0/16 \
                   172.16.0.0/12 192.0.0.0/24 192.0.2.0/24 224.0.0.0/3 \
                   198.18.0.0/15 198.51.100.0/24 203.0.113.0/24 }

set limit src-nodes 150000
set limit states 100000

table <bruteforce> persist

set block-policy drop            # Silently drop packets (stealth) instead of sending a 'Reset'
set loginterface $ext_if         # Gather packet/byte statistics for the WAN interface
set skip on lo0                  # Ignore all filtering on the loopback (local system processes)

queue outq on $ext_if bandwidth 190M
    queue q_ntp parent outq bandwidth 20M flows 1024 qlimit 1024
    queue q_std parent outq bandwidth 170M flows 1024 qlimit 1024 default

queue inq on $int_if bandwidth 195M flows 1024 qlimit 1024 default

match in all scrub (no-df random-id max-mss 1440)

match out on $ext_if scrub (no-df random-id max-mss 1440)
match out on $ext_if inet from $local_net to any nat-to ($ext_if:0)


block all                        # Default Deny: Everything is forbidden unless explicitly allowed below
antispoof quick for { $ext_if $int_if }
block in quick on $ext_if from <martians> to any
block return out quick on $ext_if from any to <martians>

block in quick from <bruteforce>

pass in inet proto icmp all icmp-type { echoreq, unreach, timex }
pass out inet proto icmp all

pass in quick on $int_if inet proto udp from $local_net to $int_if port { 67, 68 } label "DHCP"
pass in quick on $int_if inet proto tcp from $local_net to $int_if port 3128 label "Squid"
pass in quick on $int_if inet proto { tcp, udp } from $local_net to $int_if port 53 label "DNS-Local"
pass in quick on $int_if inet proto udp from $local_net to $int_if port 123 label "NTP-Local"
pass in quick on $int_if inet from $local_net to any label "LAN-to-WAN"

block in quick on $ext_if proto udp from any port { 53, 19, 1900 } to any port 123 \
    label "INT-REFLECT"

pass in quick on $ext_if inet proto tcp from any to $ext_if port 22223 \
    keep state (max-src-conn-rate 3/60, overload <bruteforce> flush global) label "SSH"

pass in quick on $ext_if inet proto udp from any to port 123 \
    keep state (max-src-nodes 150000, udp.first 10, udp.single 10, udp.multiple 10) \
    set prio 7 \
    set queue q_ntp \
    label "NTP-External"

pass out quick on $ext_if proto tcp to any port 853 label "DNS-over-TLS"

pass out quick inet 
# EOF
